# Atividade 2 — Exercícios de Limpeza, Transformação e Agrupamento de Dados

Responda as perguntas abaixo usando o dataset **emendas_tratamento.parquet**. o dataset pode ser baixado em https://drive.google.com/file/d/19ydA23-eboyiKxN29JL1EQWW4CplTiKg/view?usp=sharing.

Cada resposta deve ter:
- Uma célula de **código** com a solução
- Uma célula de **texto** (Markdown) com a sua interpretação do resultado

---
## Passo 0 — Importar pandas e carregar os dados

In [16]:
import pandas as pd
df= pd.read_parquet("C:\\Users\joao.tarik\\Downloads\\emendas_parlamentares (1).parquet")
display(df)

<>:2: SyntaxWarning: invalid escape sequence '\j'
<>:2: SyntaxWarning: invalid escape sequence '\j'
C:\Users\joao.tarik\AppData\Local\Temp\ipykernel_17964\3950775898.py:2: SyntaxWarning: invalid escape sequence '\j'
  df= pd.read_parquet("C:\\Users\joao.tarik\\Downloads\\emendas_parlamentares (1).parquet")

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ALVORADA - RS,4300604,ALVORADA,4300000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,700000.00,0.0,0.0,0.0,690900.00,9100.00,Sem informação
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000,...,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,487500.00,0.0,0.0,0.0,487500.00,0.00,Sem informação
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,100000.00,0.0,0.0,0.0,0.00,100000.00,Sem informação
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000,...,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,243750.00,0.0,0.0,0.0,243750.00,0.00,Sem informação
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,1658333.94,0.0,0.0,0.0,527200.00,1131133.94,Sem informação
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88654,201811420017,2018,Emenda Individual - Transferências com Finalid...,1142.0,ZE GERALDO,17,PARÁ (UF),Sem informação,Sem informação,1500000,...,CONSTRUCAO E AMPLIACAO DE UNIDADES OPERACIONAI...,EIND,EMENDA INDIVIDUAL,500000.00,0.0,0.0,0.0,369387.36,130612.64,201811420017
88655,201827690001,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,1,MÚLTIPLO,Sem informação,Múltiplo,3100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,EIND,EMENDA INDIVIDUAL,499975.00,499975.0,499975.0,0.0,0.00,0.00,201827690001
88656,201827690002,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,2,ITURAMA - MG,3134400,ITURAMA,3100000,...,APOIO A PROJETOS DE DESENVOLVIMENTO SUSTENTAVE...,EIND,EMENDA INDIVIDUAL,200000.00,0.0,0.0,11058.0,0.00,188942.00,201827690002
88657,201827690003,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,3,ITURAMA - MG,3134400,ITURAMA,3100000,...,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,EIND,EMENDA INDIVIDUAL,199970.00,199970.0,199970.0,0.0,0.00,0.00,201827690003
88658,201827690004,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,4,POUSO ALEGRE - MG,3152501,POUSO ALEGRE,3100000,...,APOIO A REALIZACAO DE EVENTOS DE ESPORTE AMADO...,EIND,EMENDA INDIVIDUAL,100000.00,0.0,0.0,0.0,6617.47,93382.53,201827690004

## 1) Filtre apenas as emendas do ano de **2022** e mostre as 30 primeiras linhas. Em seguida responda: Quanta emendas foram registradas em 2022?

In [19]:
df_2022 = df[df['Ano da Emenda'] == 2022]
print(df_2022.shape)

(6108, 29)

## 2) Filtre as emendas da região **Norte** que tenham `Valor Empenhado` maior que **500.000** e mostre as 5 primeiras linhas. Em seguida, responda: quantas emendas atendem a esses duas condições ao mesmo tempo?

In [20]:
df_norte_500=df[(df['Região']=='Norte') & (df['Valor Empenhado']> 500000)]
df_norte_500.head()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
18,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,MÂNCIO LIMA - AC,1200336,MÂNCIO LIMA,1200000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,616610.0,0.0,0.0,0.0,0.0,616610.0,Sem informação
120,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,VITÓRIA DO JARI - AP,1600808,VITÓRIA DO JARI,1600000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,522384.4,0.0,0.0,0.0,0.0,522384.4,Sem informação
160,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SANTANA - AP,1600600,SANTANA,1600000,...,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,0,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,4443000.0,0.0,0.0,0.0,4443000.0,0.0,Sem informação
170,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,PALMEIRAS DO TOCANTINS - TO,1713809,PALMEIRAS DO TOCANTINS,1700000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,935350.0,0.0,0.0,0.0,0.0,935350.0,Sem informação
218,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,COSTA MARQUES - RO,1100080,COSTA MARQUES,1100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,549995.0,0.0,0.0,0.0,159996.0,389999.0,Sem informação

## 3) Filtre as emendas que são do estado de **SÃO PAULO** ou do estado do **RIO DE JANEIRO** e mostre quantas linhas cada estado possui. Em seguida, responda: Qual dos dois estados possui mais emendas e quantas são?

In [27]:
sp_rj=df[(df['UF']== 'SÃO PAULO') | (df['UF']== 'RIO DE JANEIRO')]['UF'].value_counts()
sp_rj

UF
SÃO PAULO         10435
RIO DE JANEIRO     6988
Name: count, dtype: int64

## 4) Na coluna `Código da Emenda`, substitua todos os valores `"Sem informação"` por `"Não disponível"`. Mostre a contagem de valores únicos da coluna antes e depois da substituição.

In [29]:
df['Código da Emenda'] = df['Código da Emenda'].replace("Sem informação","Não disponível")
print(df['Código da Emenda'].value_counts())

Código da Emenda
Não disponível    17808
201838280001          2
201838280003          2
201838280005          2
201838280006          2
                  ...
201921520011          1
201921520012          1
201921520013          1
201917990001          1
202544840009          1
Name: count, Length: 70731, dtype: int64

## 5) Na coluna `Nome Função`, transforme todos os valores para que fiquem em letras maiúsculas. Confirme a alteração mostrando os valores únicos da coluna.

In [30]:
df['Nome Função']=df['Nome Função'].str.upper()
print(df['Nome Função'].unique())

['URBANISMO' 'COMÉRCIO E SERVIÇOS' 'SAÚDE' 'EDUCAÇÃO' 'AGRICULTURA'
 'ASSISTÊNCIA SOCIAL' 'DESPORTO E LAZER' 'DEFESA NACIONAL' 'SANEAMENTO'
 'DIREITOS DA CIDADANIA' 'GESTÃO AMBIENTAL' 'CULTURA'
 'CIÊNCIA E TECNOLOGIA' 'SEGURANÇA PÚBLICA' 'ORGANIZAÇÃO AGRÁRIA'
 'COMUNICAÇÕES' 'ADMINISTRAÇÃO' 'HABITAÇÃO' 'INDÚSTRIA' 'TRABALHO'
 'MÚLTIPLO' 'TRANSPORTE' 'PREVIDÊNCIA SOCIAL' 'ENCARGOS ESPECIAIS'
 'RELAÇÕES EXTERIORES' 'ENERGIA' 'ESSENCIAL À JUSTIÇA']

## 6) Verifique quantas linhas duplicadas existem no dataset. Em seguida, remova as duplicatas e mostre quantas linhas sobraram.

In [31]:
print(df.shape[0])
df = df.drop_duplicates()
print(df.shape[0])

88659
88596

## 7) Remova duplicatas considerando apenas as colunas `Código da Emenda` e `Município`. Quantas linhas sobraram? O resultado é diferente de quando removemos duplicatas do DataFrame inteiro?

In [33]:
df_novo= df.drop_duplicates(subset=['Código da Emenda', 'Município'])
df_novo.shape[0]

75744

## 8) Identifique quais colunas possuem valores nulos e quantos nulos cada uma tem. Em seguida, responda: qual é a coluna que possui maior número de valores nulos e quantos são?

In [34]:
df_nulos= df.isnull().sum()
df_nulos

AttributeError: 'DataFrame' object has no attribute 'snull'

## 9) Preencha os valores nulos da coluna `codigo do autor` com **-1** e os valores nulos da coluna `nome do autor da emenda` com "desconhecido" e confirme que não restaram nulos nessa coluna.

In [35]:
df['Código do Autor da Emenda']= df['Código do Autor da Emenda'].fillna(-1)
df['Nome do Autor da Emenda']= df['Nome do Autor da Emenda'].fillna("Desconhecido")

C:\Users\joao.tarik\AppData\Local\Temp\ipykernel_17964\451744434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Código do Autor da Emenda']= df['Código do Autor da Emenda'].fillna(-1)
C:\Users\joao.tarik\AppData\Local\Temp\ipykernel_17964\451744434.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nome do Autor da Emenda']= df['Nome do Autor da Emenda'].fillna("Desconhecido")

## 10) Verifique o tipo da coluna `Ano da Emenda`. Converta-a para **string** (`str`). Mostre o tipo antes e depois da conversão.

In [36]:
df['Ano da Emenda']= df['Ano da Emenda'].astype(str)

C:\Users\joao.tarik\AppData\Local\Temp\ipykernel_17964\110133046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ano da Emenda']= df['Ano da Emenda'].astype(str)

## 11) Converta a coluna `Valor Empenhado` para o tipo **float** (caso ainda não seja). Mostre o tipo após a conversão.

In [ ]:
df.info()

## 12) Calcule o **total** de `Valor Pago` por **Região**. Quais são as duas regiões que mais receberam recursos?

In [37]:
df_regiao=df.groupby('Região')['Valor Pago'].sum()
df_regiao

Região
Centro-Oeste    1.037094e+10
Exterior        2.572317e+07
Múltiplo        3.010563e+10
Nacional        7.885927e+09
Nordeste        4.644279e+10
Norte           2.034243e+10
Sudeste         3.426218e+10
Sul             1.648147e+10
Name: Valor Pago, dtype: float64

## 13) Calcule a **quantidade** de emendas por **Nome Função**. Mostre as 5 funções com mais emendas.

In [38]:
em_nome_func= df.groupby('Nome Função')['Código da Emenda'].count().sort_values(ascending=False)
em_nome_func.head()

Nome Função
SAÚDE                 37039
URBANISMO              8655
EDUCAÇÃO               8101
AGRICULTURA            4938
ENCARGOS ESPECIAIS     4610
Name: Código da Emenda, dtype: int64

## 14) Crie uma nova coluna chamada `Saldo a Pagar`. Ela deve ser o resultado da subtração entre a coluna `Valor Empenhado` e a coluna `Valor Pago`. Mostre as 5 primeiras linhas apenas com essas três colunas.

In [39]:
df['Saldo a Pagar'] = df['Valor Empenhado']= df['Valor Pago']
df['Saldo a Pagar'].head()

C:\Users\joao.tarik\AppData\Local\Temp\ipykernel_17964\336343090.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Saldo a Pagar'] = df['Valor Empenhado']= df['Valor Pago']

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Saldo a Pagar, dtype: float64

## 15) Elimine a(s) coluna(s) do dataframe que eestá totalmente vazia.

In [41]:
df = df.drop(columns='Código da Emenda_1')

## 16) Para finalizar, salve o DataFrame transformado em um arquivo no formato JSON.

In [ ]:
df.to_json()